### ISSUE TITLE
Enable GitHub hosting for the project for this fork

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/moz-codecover-ui#10]
Enable GitHub pages for the project.

**Comment by ericdesj** [comment]
I set this repo to generate a GitHub page on the `master` branch. I got the following error:
<img width="734" alt="screen shot 2017-03-01 at 2 06 58 pm" src="https://cloud.githubusercontent.com/assets/6282512/23473963/8703b172-fe88-11e6-8cab-fc3933a1d1ea.png">

I verified `_includes` and every seems to be fine (i.e. the includes).

**TODO:**
- Email Brad Kennedy see if he had a similar issue last semester
- Continue to investigate the issue

**Comment by co60ca** [comment]
I used a different repo and managed the project manually. I'm not aware of the usage of GitHub pages. See github.com/co60ca/co60ca.github.io

**Comment by ericdesj** [comment]
Ahh I see. This makes much more sense 👍 . I'll do the same, I want to setup an environment where the team can test out he new pushes.

**Comment by ericdesj** [comment]
Task completed.

- Created a new repo [here](https://github.com/ericdesj/moz-coco-w17-preview)
- The project can be viewed [here](https://ericdesj.github.io/moz-coco-w17-preview/)

**Comment by co60ca** [comment]
Suggest changing the description of this repo to point to your version of the hosted not mine so people view the up to date version.
