### ISSUE TITLE
Find, or make, a source code delivery service

### ISSUE THREAD

**Issue by klahnakoski** [ericdesj/moz-codecover-ui#16]
Last time a checked (8+ months ago) dxr.m.o did not allow cross-site scripting.  hg.m.o may not either.  If this is the case, we must setup a relay service to deliver the source code from one of these two.  I beleive the only parameters this service will require are:

* branch
* revision
* full path to file

The service will be used by the CoCo frontend when a user wishes to view a specific file, and the lines covered; I expect the traffic on this service to be very low.

Trung, the creator of the codecoverage-presentor [1] made such a relay. Contact him to see if we can use his code (a node app).  An alternative is to add an endpoint to the ActiveData service [2].

When something is ready, we can deploy it on one of ActiveData's servers 

[1] https://github.com/chinhodado/codecoverage_presenter
[2] https://github.com/klahnakoski/ActiveData/tree/master

**Comment by co60ca** [comment]
`curl -i -X OPTIONS -H "Host: dxr.mozilla.org" -H "Origin: http://co60.ca" https://dxr.mozilla.org/mozilla-central/source/ -v`

No `Access-Control-Allow-Origin: http://foo.com` as per CORS
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
So no cross-site

**Comment by marco-c** [comment]
Have you considered using the gecko-dev repository? https://github.com/mozilla/gecko-dev

**Comment by ericdesj** [comment]
Is there a way to get a file for a given revision through GH?

**Comment by marco-c** [comment]
The only thing we need is a way to go from a mercurial commit hash to a github commit hash. Once we have the GitHub commit hash, https://raw.githubusercontent.com/mozilla/gecko-dev/556a1935e6efefbd5f37959f1ae440b080089365/security/manager/ssl/CertBlocklist.cpp.

**Comment by marco-c** [comment]
Also, there's an API to get the file contents: https://developer.github.com/v3/repos/contents/.

**Comment by klahnakoski** [comment]
Do not use the github mirror, it does not have all branches, and I am not certain it has all changeset either; just snapshots of what's in ?inbound?

**Comment by klahnakoski** [comment]
dxr may also suffer the same problems: Not all historical revisions are represented.

**Comment by klahnakoski** [comment]
Maybe hg is best, where you can select the branch and revision, and you get formatted code.  Some fancy marking of the covered lines with the right css style might just work.

https://hg.mozilla.org/integration/mozilla-inbound/file/722daec5cc3e/browser/components/downloads/content/contentAreaDownloadsView.js

**Comment by marco-c** [comment]
> Do not use the github mirror, it does not have all branches, and I am not certain it has all changeset either; just snapshots of what's in ?inbound?

I think most branches are there (https://developer.mozilla.org/en-US/docs/Mozilla/Git).
The `master` branch corresponds to `mozilla-central`, the `inbound` branch corresponds to `mozilla-inbound`, etc.
The benefit of this would be to avoid a relay service.

**Comment by marco-c** [comment]
Here's the API to get a GitHub commit hash from a Mercurial one: https://wiki.mozilla.org/ReleaseEngineering/Applications/Mapper.

E.g. https://api.pub.build.mozilla.org/mapper/gecko-dev/rev/hg/75df8909061c.

**Comment by marco-c** [comment]
Ah, something to keep in mind is that some source files are actually in the build directory (generated when compiling). For example, source files generated by the IPDL compiler.

**Comment by ericdesj** [comment]
I got a relay service up and running on Heroku (until other hosting arrangements are made).

Here's an example of it in action with @klahnakoski 's last post:
> Maybe hg is best, where you can select the branch and revision, and you get formatted code. Some fancy marking of the covered lines with the right css style might just work.
 https://hg.mozilla.org/integration/mozilla-inbound/file/722daec5cc3e/browser/components/downloads/content/contentAreaDownloadsView.js

We have two formats:

- **Raw** `mozilla_hg_raw?branch={BRANCH}?revision={REVSION}?path={path}`
  - https://still-scrubland-32510.herokuapp.com/mozilla_hg_raw?branch=integration/mozilla-inbound/&revision=722daec5cc3e&path=browser/components/downloads/content/contentAreaDownloadsView.js

- **HTML** `mozilla_hg?branch={BRANCH}?revision={REVSION}?path={path}`
  - https://still-scrubland-32510.herokuapp.com/mozilla_hg?branch=integration/mozilla-inbound/&revision=722daec5cc3e&path=browser/components/downloads/content/contentAreaDownloadsView.js
  - We can use the CSS for the syntax highlighting. Example [here](https://still-scrubland-32510.herokuapp.com/mozilla_hg_example)
