### ISSUE TITLE
Add language indicator on revision dropdown?

### ISSUE THREAD

**Issue by klahnakoski** [ericdesj/moz-codecover-ui#25]
We have a "source.language" property.  It is not yet filled for all sources, but it can be used to distinguish the language being covered.

I am not sure if there should be a language dropdown (and then a further revision drop down), or maybe the revision drop down will simply include the language.

**Comment by ericdesj** [comment]
PR is up for this task #26 .

This is the first iteration. I will look into implementing a two step-process that will display a language selector first and then display the revisions.
